### ISSUE TITLE
Contao 5.0 compatibility

### ISSUE THREAD

**Issue by b42n1** [heart-bits/contao-recipes#1]
The extension is currently not compatible with Contao 5.0. Any plans to update the compatibility in the near future?

I found and tested the extension a few days ago and the basis is very solid, even if you still have to adjust a few things like recipe schema markup.

It would be nice if the extension would be further developed. It is probably currently the best recipe extension for Contao, even if not too many have discovered it yet.

Greetings

**Comment by saschawustmann** [comment]
Hi @barnabashohl,

first of all, thanks for the compliment on the extension - Much appreciated!

This will of course be updated for Contao 5. But since my free time for my extensions has been very limited, this will probably take some time. It will for sure be updated for the next LTS 5.3 at the latest, though.

So, if you can, please use this extension with the current LTS version 4.13 or feel free to do some needed changes yourself in a PR! But i hope to deliver an update on this myself very soon!

**Comment by saschawustmann** [comment]
@b42n1, took me long enough, sorry!

The migrations might be buggy, but otherwise you should be able to install and work with the extension (Version 0.2.0) and Contao 5.3 as expected.
When you find the time, it would be great to get your feedback on this!

Thanks
